data_path: /home/eugenia/progetti/ContinualLearning/data/mvtech
save_dir: example
save_dir_rocauc: roc_auc_curves
img_size: 256
validation_ratio: 0.2

latent_dim: 512
num_epochs: 50
batch_size: 32
b1: 0.5
b2: 0.99
lr: 0.0002

lambda_adv: 1
lambda_con: 40
lambda_enc: 1

early_stopping: True
lr_scheduler: True
